apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljyt-portal-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ljyt-portal-prod
  template:
    metadata:
      labels:
        app: ljyt-portal-prod
    spec:
      serviceAccount: ljyt
      serviceAccountName: ljyt
      containers:
        - name: ljyt-portal-prod
          image:  zpk.abc:443/jk-docker-prod/ljyt/ljyt-portal/ljyt-front:1.p.20210804.2
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
          command:
            - /opt/rh/rh-nginx112/root/usr/sbin/nginx
          args:
            - '-c'
            - /opt/rh/rh-nginx112/register.content/etc/opt/rh/rh-nginx112/nginx/nginx.conf
            - '-g'
            - daemon off;
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: en_US.utf8
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9990
          volumeMounts:
            - name: ljyt-portal-prod
              mountPath: /opt/rh/rh-nginx112/register.content/etc/opt/rh/rh-nginx112/nginx/nginx.conf
              subPath: nginx.conf
      imagePullSecrets:
        - name: fintechzpk
      volumes:
        - name: ljyt-portal-prod
          configMap:
            name: nginx-config-ljyt-portal-prod
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: ljyt-portal-prod
spec:
  ports:
    - port: 9990
      name: ljyt-portal-prod
  selector:
    app: ljyt-portal-prod
---
apiVersion: v1
kind: Route
metadata:
  name: ljyt-portal-prod
spec:
  host: ljyt-portal-prod.apps.fintech.paas.test.abc
  path: /
  to:
    kind: Service
    name: ljyt-portal-prod
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-ljyt-portal-prod
data:
  nginx.conf: |
    worker_processes  auto;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        server_tokens off;
        server_names_hash_bucket_size 128;
        client_header_buffer_size 2k;
        large_client_header_buffers 4 4k;
        client_max_body_size 50M;
        client_body_buffer_size 50M;
        proxy_buffer_size 64k;
        proxy_buffers 4 32k;
        proxy_busy_buffers_size 64k;
        proxy_temp_file_write_size 64k;
        keepalive_timeout 1800;
        client_header_timeout 10;
        client_body_timeout 10;
        reset_timedout_connection on;
        send_timeout 10;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" "$http_user_agent"'
                          '"客户端地址:"$http_x_forwarded_for'
                          '"服务器地址:"$server_addr'
                          ' "$upstream_addr"  "$upstream_cache_status" "$request_body"'
                          '"服务器域名:"$server_name';
        sendfile on;
        gzip on;
        gzip_min_length 1k;
        gzip_buffers 16 64k;
        gzip_http_version 1.1;
        gzip_comp_level 6;
        gzip_types text/plain application/x-javascript application/json text/xml text/css application/xml application/javascript text/javascript img/png img/jpeg image/png image/jpeg;
        gzip_vary on;
        add_header X-Frame-Options SAMEORIGIN;
        add_header Cache-Control no-store ;
        add_header Content-Security-Policy 'default-src "self";script-src "self";frame-ancestors "self";object-src "none"';
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection '1; mode=block'; 

        server {
            listen       9990;
            listen       [::]:9990 ipv6only=on;
            server_name  localhost;
            server_tokens off;
            access_log  /var/log/nginx/access.log  main;
            error_log  /var/log/nginx/nginx_error.log error;
            add_header X-Frame-Options SAMEORIGIN;
            root /opt/app-root/src/oc-build/deployments/dist;
            proxy_connect_timeout 600;
            proxy_read_timeout 600;
            proxy_send_timeout 600;
            proxy_redirect ~*http://(.*?)[^/]+(/.*)  http://$http_host$2;
            add_header Cache-Control no-store ;
            #location / {
            #    try_files $uri /index.html;
            #}
            location / {
              root /opt/app-root/src/oc-build/deployments/dist;
              try_files $uri /index.html;
              index /opt/app-root/src/oc-build/deployments/dist/index.html;
            }
            location  /ljytbase/ {
                proxy_pass http://ljyt-back-prod:9527/ljytbase/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            location ~*\.(htm|html)$ {
               expires -1;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }


